alias ..='cd ..'
alias beh='tac ~/.bash_eternal_history'
alias c='cat'
alias cdt='cd "$_"'
alias copy='reattach-to-user-namespace pbcopy'
alias e="emacsclient -n"
alias ep='emacs_pipe'
alias ee="emacs -nw -q"
alias ef='efind'
alias eg='egit'
alias f='find'
alias fromip="who | grep \"^$USER\" | sed 1q | perl -n -e 's,.*\(([0-9.]+)\),\1, and print'"

# git aliases
alias gb='git branch'
alias gbd='git branch-by-date'
alias gc='git checkout'
alias gcbz='git branch -D z 2> /dev/null ; git checkout -b z'
alias gconf='git config'
alias gconfl='git config -l'
alias gcl='git clean'
alias gcln='git clean -nd'
alias gcm='git branch master origin/master && git checkout master'
alias gco='git commit'
alias gcoa='git commit --amend'
alias gd='git diff'
alias gf='git fetch'
alias gdc='git diff --cached'
alias gdcs='git diff --cached --stat=200,200'
alias gdsc='git diff --cached --stat=200,200'
alias gdw='git diff --word-diff'
alias gds='git diff --stat=200,200'
alias ghci='ghci -fwarn-incomplete-patterns'
alias gl='git log'
alias gld='git log --author=dan'
alias gp='git pull'
alias gpo='git pull origin'
alias gpom='git pull origin master'
alias gr='git reset'
alias grh='git reset --hard'
alias grhh='git reset --hard HEAD'
alias gs='git show'
alias gst='git stash'
alias gsta='git stash apply'
alias gsts='git stash save `date "+%Y-%m-%d %H:%M"`'
alias gstp='git stash pop'
alias gstsp='git stash show -p'
alias gsl='git stash list'
alias gss='git show --stat=120,120'
alias glh='git log --oneline -n 20'
alias gls='git ls-files'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbi='git rebase --interactive'
alias gri='git rebase --interactive'
alias git-init='git init && git add * && git commit -m "init"'
alias git-squash='git reset --soft HEAD~1 && git commit --amend -C HEAD'

alias gitk-all='gitk --all --simplify-by-decoration'
alias g='grep'
alias gless='grep --color=always | less -R'
alias grep='grep --color=auto'
alias h='head'
alias hist='tac ~/.zsh_history'
alias jp=jsonpipe
alias less='less -SX'
alias l='less'
alias ctl='(column -t | less -SX) <'
alias ls='ls --color=tty --hide="*.pyc" --hide="#*"'
alias lh='ls -lh'
alias ll='ls -lh'
# alias ll='ls -l --color=always | perl -p -e "s,([^ ]+ +){8},,"'
alias lt='ls -lht'
alias mkdir='mkdir -p'
alias mk='mkdir'
alias m='more'
alias path='readlink -f'
alias p=path
alias python='python -W ignore:Module:UserWarning -W ignore::DeprecationWarning -W ignore::PendingDeprecationWarning'
alias pwdr='pwd | sed "s,.*$HOME/,,"'
alias ping-www='ping www.direct.gov.uk'
alias ps-me='ps -u `whoami`'
# alias rsync='rsync --exclude=.git'
alias R='R --silent --no-restore --no-save --vanilla'
alias rs='rsync -z --progress'
alias s=show
alias thg='tac ~/.zsh_history | grep'
alias tm='tree | more'
alias tree='tree -AC --noreport'
alias t='tree'
alias tl='topleft'
alias tail-messages='tail -f /var/log/messages'
if [ $(uname) = "Darwin" ] ; then
    alias hibernateon="sudo pmset -a hibernatemode 5"
    alias hibernateoff="sudo pmset -a hibernatemode 0"
else
    alias top='top -d.8'
    alias s='sync-dirs'
    alias ps2pdf='ps2pdf -dAutoRotatePages=/None'
    alias mutt='LANG=en mutt -y'
    alias gt='gthumb'
    alias exit='sync-history ; builtin exit'
    alias fusermount='fusermount -uz'
    alias mu='mutt'
    alias screen-external='xrandr --auto && xrandr --output LVDS1 --off && pgrep compiz && compiz --replace &'
    alias screen-internal='xrandr --auto && xrandr --output VGA1 --off'
    alias xdvi='xdvi -expert -s 5'
    alias xpdf='xpdf -fullscreen -bg white'
fi
