path=(
    ~/bin
    ~/.local/bin
    ~/src/devenv/temporal/tools
    ~/src/devenv/tools/bash
    ~/src/devenv/emacs-config/bin
    ~/go/bin
    ~/.cargo/bin
    /opt/homebrew/opt/gnu-sed/libexec/gnubin
    /opt/homebrew/opt/coreutils/libexec/gnubin
    /opt/homebrew/sbin
    /opt/homebrew/bin
    /Library/TeX/texbin
    $path
)
