path=(
    ~/bin
    ~/.local/bin
    ~/src/devenv/temporal/tools
    ~/src/devenv/temporal/tools/oss-cicd
    ~/src/devenv/tools/bash
    ~/src/devenv/emacs-config/bin
    ~/go/bin
    ~/.cargo/bin
    /opt/homebrew/opt/gnu-sed/libexec/gnubin
    /opt/homebrew/opt/coreutils/libexec/gnubin
    /opt/homebrew/sbin
    /opt/homebrew/bin
    $JAVA_HOME/bin
    /opt/homebrew/opt/dotnet@8/bin
    /opt/homebrew/opt/ruby/bin
    /Library/TeX/texbin
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /Library/Apple/usr/bin
)
