#!/bin/bash

alias beh='tac ~/.bash_eternal_history'
alias c='cat'
alias cdt='cd $_'
alias e='emacsclient'
alias et="emacsclient -t --alternate-editor=''"
alias f='find'
alias g='grep'
alias gb='git branch'
alias gc='git checkout'
alias gcm='git checkout master'
alias gd='git diff'
alias gl='git log'
alias glh='git log --oneline -n 20'
alias gls='git ls-files'
alias gri='git rebase -i'
alias gst='git status'
alias gitk-all='gitk --all --simplify-by-decoration'
alias h='head'
alias jp=jsonpipe
alias less='less -S'
alias l='less'
alias ls='ls --color=tty --hide=*.pyc --hide=#*'
alias ll='ls -lh'
alias lt='ls -lht'
alias mk='mkdir'
alias m='more'
alias org='cd ~/lib/emacs/org'
alias pwdr='pwd | sed "s,$HOME/,,"'
alias ping-www='ping www.direct.gov.uk'
alias ps-me='ps -u `whoami`'
alias reload='. ~/.bashrc'
alias rsync='rsync --exclude=.git'
alias R='R --silent --no-restore --no-save --vanilla'
alias s=show
alias sync-history='history -a ; history -n'
alias tm='tree | more'
alias tree='tree -AC --noreport'
alias t='tree'
alias tl='topleft'
alias tail-messages='tail -f /var/log/messages'
if [ "$_system" = "Darwin" ] ; then
    alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
    alias hibernateon="sudo pmset -a hibernatemode 5"
    alias hibernateoff="sudo pmset -a hibernatemode 0"
else
    alias top='top -d.8'
    alias s='sync-dirs'
    alias ps2pdf='ps2pdf -dAutoRotatePages=/None'
    alias mutt='LANG=en mutt -y'
    alias gt='gthumb'
    alias exit='sync-history ; builtin exit'
    alias fusermount='fusermount -uz'
    alias mu='mutt'
    alias screen-external='xrandr --auto && xrandr --output LVDS1 --off && pgrep compiz && compiz --replace &'
    alias screen-internal='xrandr --auto && xrandr --output VGA1 --off'
    alias xdvi='xdvi -expert -s 5'
    alias xpdf='xpdf -fullscreen -bg white'
fi


if [ "$_system" = "Darwin" ] ; then
    export BROWSER=google-chrome
else
    export BROWSER=google-chrome
fi
export EDITOR=emacsclient

[ "$_system" = "Darwin" ] && {
    for path in $(cat <<EOF
/usr/local/bin
/usr/local/share/python
/usr/local/Cellar/python/2.7.2/bin
/usr/texbin
/usr/local/share/npm/bin
EOF
) ;
    do
	export PATH=$path:$PATH
    done

    export PGDATA=/usr/local/var/db/postgresql/defaultdb
    export PYTHON_SITE_PACKAGES=/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages
} || {
    export PATH=/usr/local/src/postgresql/bin:$PATH
}

export PATH=$HOME/bin:$PATH
export NODE_PATH=/usr/local/lib/node

. ~/config/bash/extra.sh

function _dan_uniquify_path {
    echo "$1" | perl -p -e 's/:/\n/g' | awk '!_[$0]++' | perl -p -e 's/\n/:/g'
}

export PATH=$(_dan_uniquify_path $PATH)
export PYTHONPATH=$(_dan_uniquify_path $PYTHONPATH)
export NODEPATH=$(_dan_uniquify_path $NODEPATH)
