#!/bin/bash

## aliases
alias c='cat'
alias cdt='cd $_'
alias e='emacsclient'
alias et="emacsclient -t --alternate-editor=''"
alias f='find'
alias g='grep'
alias gb='git branch'
alias gc='git checkout'
alias gcm='git checkout master'
alias gd='git diff'
alias gl='git log'
alias glh='git log --oneline -n 20'
alias gls='git ls-files'
alias gri='git rebase -i'
alias gst='git status'
alias gitk-all='gitk --all --simplify-by-decoration'
alias h='head'
alias less='less -S'
alias l='ls -1'
alias ll='ls -lh'
alias lt='ls -lht'
alias ls='ls --color=tty'
alias mk='mkdir'
alias m='more'
alias org='cd ~/lib/emacs/org'
alias ps-me='ps -u `whoami`'
alias reload='. ~/.bashrc'
alias R='R --silent --no-restore --no-save --vanilla'
alias sshfs='sshfs -o idmap=user'
alias sync-history='history -a ; history -n'
alias tm='tree | more'
alias tree='tree -AC --noreport'
alias t='tree'
alias tl='topleft'
alias tail-messages='tail -f /var/log/messages'
if [ "$_system" = "Darwin" ] ; then
    alias emacs='/Applications/Emacs.app/Contents/MacOS/Emacs'
    alias hibernateon="sudo pmset -a hibernatemode 5"
    alias hibernateoff="sudo pmset -a hibernatemode 0"
else
    alias top='top -d.8'
    alias s='sync-dirs'
    alias ps2pdf='ps2pdf -dAutoRotatePages=/None'
    alias mutt='LANG=en mutt -y'
    alias gt='gthumb'
    alias exit='sync-history ; builtin exit'
    alias fusermount='fusermount -uz'
    alias mu='mutt'
    alias screen-external='xrandr --auto && xrandr --output LVDS1 --off && pgrep compiz && compiz --replace &'
    alias screen-internal='xrandr --auto && xrandr --output VGA1 --off'
    alias xdvi='xdvi -expert -s 5'
    alias xpdf='xpdf -fullscreen -bg white'
fi


## Exports
if [ "$_system" = "Darwin" ] ; then
    export BROWSER=firefox
else
    export BROWSER=google-chrome
fi
export EDITOR=emacsclient

export luscinia=dan@luscinia.princeton.edu
export tichodroma=dan@tichodroma.princeton.edu
export yakuba=dan@yakuba.princeton.edu
export oak=davison@oak.well.ox.ac.uk
export ash=davison@ash.well.ox.ac.uk
export gate=davison@gate.stats.ox.ac.uk ## 163.1.210.59 ## 
export genecluster=davison@genecluster.stats.ox.ac.uk ##'163.1.210.63'
export wtchg_cluster=davison@login1-cluster1.well.ox.ac.uk
export arizona=ddavison@arizona.princeton.edu
export cetus=ddavison@cetus.princeton.edu
export trogon=martin@192.168.2.3

export PYTHONPATH=~
[ "$_system" = "Darwin" ] && {
    for path in $(cat <<EOF
/usr/local/bin
/usr/local/Cellar/python2.6/2.6.5/bin
EOF
) ;
    do
	export PATH=$path:$PATH
    done
} || {
    export PATH=/usr/local/src/postgresql/bin:$PATH
}
export PATH=$HOME/bin:$PATH
# Delete duplicated elements in $PATH
export PATH=$(echo $PATH | perl -p -e 's/:/\n/g' | awk '!_[$0]++' | perl -p -e 's/\n/:/g')
export NODE_PATH=/usr/local/lib/node

