_cwd=$(pwd)
cd ~/config/shell

source zsh/zsh.sh
source lib.sh
source env.sh
source zsh/path.sh
source prompt.sh
# source history.sh
source ~/lib/git/contrib/completion/git-functions.sh
source autojump.sh
# source readline.sh
source dircolors.sh
source alias.sh
[ -f extra.sh ] && source extra.sh

cd "$_cwd"
# The following lines were added by compinstall

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' verbose false
zstyle :compinstall filename '/Users/davison/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
